apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: pwnies-please
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
    ports:
      - protocol: "TCP"
        port: 80
        targetPort: 5000
  healthcheck:
    # TIP: disable the healthcheck during development
    enabled: false
  image: us.gcr.io/dotted-forest-314903/pwnies-please-challenge:24c2e38201e37463bbbaec74e29a7d8bc943d7d5aa866f1c6791811843cb5328
